import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { Modal, Button, FormField, TextField, TextArea, Select, Stack, Alert, Inline } from "@/components/hms";
import { supabase } from "@/integrations/supabase/client";
import type { TablesInsert, Enums } from "@/integrations/supabase/types";
import { useLocations } from "@/hooks/useLocations";
import type { useAuditLog } from "@/hooks/useAuditLog";

interface NewIncidentModalProps {
  open: boolean;
  onClose: () => void;
  residentId: string;
  branchId: string;
  staffId: string;
  logAction: ReturnType<typeof useAuditLog>["logAction"];
}

const TYPES = ["FALL", "MEDICATION_ERROR", "BEHAVIOUR", "MEDICAL_EMERGENCY", "EQUIPMENT", "OTHER"] as const;
const SEVERITIES = ["LOW", "MEDIUM", "HIGH", "CRITICAL"] as const;
type IncidentType = (typeof TYPES)[number];
type Severity = Enums<"incident_severity">;

function todayISO(): string {
  return new Date().toISOString().slice(0, 10);
}

export function NewIncidentModal({ open, onClose, residentId, branchId, staffId, logAction }: NewIncidentModalProps) {
  const { t } = useTranslation();
  const qc = useQueryClient();
  const { flatList } = useLocations(branchId);

  const now = new Date();
  const [type, setType] = useState<IncidentType>("FALL");
  const [severity, setSeverity] = useState<Severity>("LOW");
  const [date, setDate] = useState<string>(todayISO());
  const [hour, setHour] = useState<string>(String(now.getHours()).padStart(2, "0"));
  const [locationId, setLocationId] = useState<string>("");
  const [description, setDescription] = useState("");
  const [immediateAction, setImmediateAction] = useState("");
  const [followUpDue, setFollowUpDue] = useState("");
  const [saving, setSaving] = useState(false);
  const [err, setErr] = useState<string | null>(null);

  useEffect(() => {
    if (open) {
      const n = new Date();
      setType("FALL");
      setSeverity("LOW");
      setDate(todayISO());
      setHour(String(n.getHours()).padStart(2, "0"));
      setLocationId("");
      setDescription("");
      setImmediateAction("");
      setFollowUpDue("");
      setErr(null);
    }
  }, [open]);

  const locationOptions = [
    { value: "", label: "—" },
    ...flatList
      .filter((l) => l.type === "ROOM" || l.type === "BED")
      .map((l) => ({ value: l.id, label: `${l.code} · ${l.name_zh ?? l.name}` })),
  ];

  const isHighSeverity = severity === "HIGH" || severity === "CRITICAL";

  const handleSave = async () => {
    if (!description.trim()) {
      setErr(t("incidents.description"));
      return;
    }
    setSaving(true);
    setErr(null);
    try {
      const occurredAt = new Date(`${date}T${hour}:00:00`).toISOString();
      const insertRow: TablesInsert<"incidents"> = {
        branch_id: branchId,
        resident_id: residentId,
        type,
        severity,
        occurred_at: occurredAt,
        location_id: locationId || null,
        reporter_id: staffId,
        description: description.trim(),
        immediate_action: immediateAction.trim() || null,
        follow_up_due_at: followUpDue ? new Date(`${followUpDue}T23:59:00`).toISOString() : null,
        status: "OPEN",
        // incident_ref auto-generated by DB trigger; pass empty placeholder so insert type is satisfied.
        incident_ref: "",
      };
      const { data, error } = await supabase.from("incidents").insert(insertRow).select().single();
      if (error) throw error;
      await logAction({
        action: "INCIDENT_REPORTED",
        entity_type: "incidents",
        entity_id: data.id,
        branch_id: branchId,
        after_state: data as unknown as Record<string, unknown>,
        metadata: { severity, type },
      });
      void qc.invalidateQueries({ queryKey: ["incidents", branchId, residentId] });
      void qc.invalidateQueries({ queryKey: ["incidents"] });
      toast.success(t("incidents.createSuccess"));
      if (isHighSeverity) toast.warning(t("incidents.highSeverityAlert"));
      onClose();
    } catch (e) {
      setErr(e instanceof Error ? e.message : "Failed");
    } finally {
      setSaving(false);
    }
  };

  return (
    <Modal
      open={open}
      onClose={onClose}
      title={t("incidents.new")}
      size="lg"
      footer={
        <>
          <Button variant="ghost" onClick={onClose} disabled={saving}>{t("actions.cancel")}</Button>
          <Button variant="primary" loading={saving} onClick={handleSave}>{t("actions.save")}</Button>
        </>
      }
    >
      <Stack gap={3}>
        {err && <Alert severity="error" description={err} />}
        {isHighSeverity && (
          <Alert severity="warning" description={t("incidents.highSeverityAlert")} />
        )}
        <Inline gap={3} className="w-full">
          <div style={{ flex: 1 }}>
            <FormField label={t("incidents.detail")} required>
              <Select
                value={type}
                onChange={(e) => setType((e.target as HTMLSelectElement).value as IncidentType)}
                options={TYPES.map((tp) => ({ value: tp, label: t(`incidents.type.${tp}`) }))}
              />
            </FormField>
          </div>
          <div style={{ flex: 1 }}>
            <FormField label={t("incidents.severity.LOW").replace(t("incidents.severity.LOW"), t("residents.columns.status"))} required>
              <Select
                value={severity}
                onChange={(e) => setSeverity((e.target as HTMLSelectElement).value as Severity)}
                options={SEVERITIES.map((s) => ({ value: s, label: t(`incidents.severity.${s}`) }))}
              />
            </FormField>
          </div>
        </Inline>
        <Inline gap={3} className="w-full">
          <div style={{ flex: 1 }}>
            <FormField label={t("incidents.occurredAt")} required>
              <TextField type="date" value={date} onChange={(e) => setDate(e.target.value)} />
            </FormField>
          </div>
          <div style={{ flex: 1 }}>
            <FormField label={t("tasks.dueTime")}>
              <Select
                value={hour}
                onChange={(e) => setHour((e.target as HTMLSelectElement).value)}
                options={Array.from({ length: 24 }, (_, i) => {
                  const h = String(i).padStart(2, "0");
                  return { value: h, label: `${h}:00` };
                })}
              />
            </FormField>
          </div>
        </Inline>
        <FormField label={t("incidents.location")}>
          <Select
            value={locationId}
            onChange={(e) => setLocationId((e.target as HTMLSelectElement).value)}
            options={locationOptions}
          />
        </FormField>
        <FormField label={t("incidents.description")} required>
          <TextArea rows={4} value={description} onChange={(e) => setDescription(e.target.value)} />
        </FormField>
        <FormField label={t("incidents.immediateAction")}>
          <TextArea rows={3} value={immediateAction} onChange={(e) => setImmediateAction(e.target.value)} />
        </FormField>
        <FormField label={t("incidents.followUpDue")}>
          <TextField type="date" value={followUpDue} onChange={(e) => setFollowUpDue(e.target.value)} />
        </FormField>
      </Stack>
    </Modal>
  );
}
